name: CI Pipeline to staging/production environment
on:
  pull_request:
    branches:
      - staging
      - main
    paths:
      - 'backend/**'
      - '.github/**'
jobs:
  test:
    runs-on: ubuntu-latest
    name: Setup, test, and build project
    env:
      PORT: 5000
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: ./backend
        run: npm ci

      - name: Test application
        working-directory: ./backend
        run: npm test

      - name: Build application
        working-directory: ./backend
        run: |
          echo "Run command to build the application if present"
          npm run build --if-present